### PR TITLE
Added nba-multichain-betting as a submodule

### PR DESCRIPTION
**Pull request by daningyn**
Please checkout at live site: https://polymer-bet.daningyn.xyz/
For local site: please follow README instruction to build

### CODE REVIEW

**Comment by tmsdkeys** [comment]
Hey @daningyn thanks for submitting! We'll try to review whenever we get a chance!

**Comment by daningyn** [comment]
@tmsdkeys I forgot to tell you, I already have the demo video for this. 
https://www.youtube.com/watch?v=rMzEye7GUMw&t=2s

**Comment by daningyn** [comment]
For the lottery app, please check out here
https://www.youtube.com/watch?v=bz3D4Q1DcKw

**Comment by kenobijon** [comment]
Hey @daningyn could you please add in the information about each of these dApps in explore-apps.md

**Comment by daningyn** [comment]
Hi @kenobijon, I have added the information in explorer-apps.md

**Review by kenobijon — APPROVED** [review]
LGTM

**Pull request merged**
