### PR TITLE
nft vote application

### PR DESCRIPTION
**Pull request by kenobijon**
- Adding Polymer IBC Ballot Voting and NFT Minting App to Community Demo Apps

### CODE REVIEW

**Comment by tmsdkeys** [comment]
Would be good as an example yes, but let's also update the explore-apps.md file according to the template to set best practice

**Review by tmsdkeys — APPROVED** [review]
See comment above

**Comment by kenobijon** [comment]
@tmsdkeys I'd recommend updating the README. Right now it reads as 3 separate options to me as opposed to combining or using all three. 

May something like:

Add Project to explore-apps.md

Option 1: Direct Contribution
Option 2: Add Submodule 

Open to ideas but I'll update the explore-apps.md file and make suggestions to the README

**Review by tmsdkeys — APPROVED** [review]
LGTM

**Pull request merged**
