### PR TITLE
Added Polymer Lottery Contract as a submodule

### PR DESCRIPTION
**Pull request by tuananhht94**
Please check out the live site at: https://lottery.tuananh.xyz/.

For the local site, please follow the instructions in the README to build it.

You can also view a demo video here: https://youtu.be/iveqCe5V9YA.

### CODE REVIEW

**Review by tmsdkeys — CHANGES_REQUESTED** [review]
Hey @tuananhht94 thanks for your submission!

I think you should instead link to the https://github.com/tuananhht94/polymer-lottery-contract repo...

For our purposes this is more relevant than the frontend repo. Can you update this is in the gitmodules file and add links to the live application in its readme? 🙏

**Comment by anhhtvip** [comment]
Dear @tmsdkeys ,

Thank you for your guidance!
I've updated the gitmodules file to link to the https://github.com/tuananhht94/polymer-lottery-contract repository, as you suggested.
Additionally, I've added links to the live application in the README of that repository.

Could you please review the changes and proceed with merging if everything looks good to you?

**Comment by tuananhht94** [comment]
Dear @tmsdkeys ,

Thank you for your guidance!
I've updated the gitmodules file to link to the https://github.com/tuananhht94/polymer-lottery-contract repository, as you suggested.
Additionally, I've added links to the live application in the README of that repository.

Could you please review the changes and proceed with merging if everything looks good to you?

**Review by tmsdkeys — APPROVED** [review]
Thanks for applying the changes! Approved

**Pull request merged**
