### PR TITLE
Create index.html

### PR DESCRIPTION
**Pull request by FatihCelebi**

### CODE REVIEW

**Comment by FatihCelebi** [comment]
new

**Comment by kenobijon** [comment]
Hey could you please not delete explore-apps.md. Could you also please provide a description of what this PR is for

**Comment by FatihCelebi** [comment]
hi,
I added explore-apps.md and description for index.html

Thank u

Ken Jon ***@***.***>, 14 Mar 2024 Per, 21:52 tarihinde şunu
yazdı:

**Comment by kenobijon** [comment]
Hi @FatihCelebi,

Thank you for your contribution to the project! 

I've reviewed the commits you've added, including the creation of index.html and explore-apps.json, as well as the updates to the README.md file. It's great to see your initiative in enhancing the project's documentation and structure.

However, it appears there may have been a misunderstanding regarding the project requirements. Specifically, we are looking for demo projects that utilize Polymer, and it seems the submitted explore-apps.md was expected but instead, an explore-apps.json was created. Additionally, the project contribution appears to include a snippet of HTML code rather than a Polymer-based project.

Could I kindly ask you to resubmit your demo project with the following adjustments?

1. Utilize Polymer for the demo project to align with our project's framework and goals.
2. Ensure that the contribution includes a explore-apps.md file, or if the .json format is intentional, please provide a brief explanation or documentation on the reasoning

**Pull request closed without merging**
