### PR TITLE
Raffle Proof System DApp

### PR DESCRIPTION
**Pull request by yavuzkocca**
This application enables a user to enter a Raffle on a contract on OP Sepolia. After the raffle is completed, the winner gets a ERC-721 NFT for free on Base Sepolia even though the users entered via OP Sepolia.

Uses Polymer x IBC as the cross-chain format

Commits to the spirit of application specific chains/rollups where entering the raffle function can be specialized on one chain, NFT distribution to the winner of the raffle on another and both can form composable applications through interoperability.

### CODE REVIEW

**Review by kenobijon — APPROVED** [review]
Looks good to me!

**Comment by yavuzkocca** [comment]
Good to hear. will you merge?

**Review by tmsdkeys — APPROVED** [review]
Hey thanks for submitting! I'll go ahead and give an approval as well but I'd recommend two changes to the origin repo still:

1. The verify command on base is incorrect, it does not need the NFT image URL as argument (contract hard codes it)
2. When building a frontend, I would strongly recommend you make the send-packet action part of the user flow in the UI. Meaning: when someone ends the raffle, the packet gets sent automatically + given that packets can fail, add a button to retry (to avoid spamming you could add access control)

But your repo is well documented so that helps the dev figure out what to do.

**Comment by tmsdkeys** [comment]
@yavuzkocca Check to see if implementing my recommendations is a low lift. If not, you should be able to merge the PR given our approvals and implement them at a later time in your repo

**Pull request closed without merging**
